### ISSUE TITLE
Setup Circle CI to build and deploy in Heroku

### ISSUE THREAD

**Issue by emmeblm** [slincastro/covid19-data-aggregator#3]

**Comment by emmeblm** [comment]
@slincastro creo que lo mejor es que tu agregues el proyecto en tu cuenta de circleci ya que eres el owner del repo, para que todo el ownership quede contigo... Cuando hayas hecho eso, me puedes agregar como colaboradora tambien para poder setear las variables de ambiente necesarias para el job de deploy.. te parece?

**Comment by slincastro** [comment]
ese es el link del proyecto de circle ci https://app.circleci.com/pipelines/github/slincastro/covid19-data-aggregator
